import React from 'react';
import { View, Text, StyleSheet, TouchableOpacity, Linking, Alert } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import MyCard from './MyCard'; 
import { CarouselWidget } from './CarouselWidget'; // ✅ Import new Carousel component
import { InstructorWidget, InstructorItem } from '../types';
import { theme } from '../theme';

interface WidgetRendererProps {
    widget: InstructorWidget;
}

/**
 * WidgetRenderer
 * * This component acts as a "Factory". It takes a raw widget object 
 * * (generated by Gemini) and decides which UI layout to render.
 * * It supports:
 * * 1. Horizontal Scroll (Carousel) for lists (Top 5 Places, Music, Outfits, etc.)
 * * 2. Visual Cards for Single Outfits/Recipes
 * * 3. Text Cards for Scripts/Quotes
 * * 4. Action Cards for Tasks
 */
export const WidgetRenderer: React.FC<WidgetRendererProps> = ({ widget }) => {
    const { type, title, subtitle, content, priority, actionLabel } = widget;

    // --- 1. CAROUSEL CHECK (The "Netflix" Logic) ---
    // If the widget is a list type and contains an 'items' array, render the CarouselWidget.
    const isCarouselType = [
        'place_card', 
        'music_playlist', 
        'movie_list', 
        'book_list',
        'outfit_guide', 
        'gift_guide',   
        'date_idea'     
    ].includes(type);
    
    // Check if content.items exists and has data
    if (isCarouselType && content.items && content.items.length > 0) {
        
        // Handlers for individual item feedback (can be connected to store later)
        const handleItemLike = (item: InstructorItem) => console.log("Liked:", item.title);
        const handleItemDislike = (item: InstructorItem) => console.log("Disliked:", item.title);

        return (
            <CarouselWidget 
                widget={widget} 
                onItemLike={handleItemLike} 
                onItemDislike={handleItemDislike} 
            />
        );
    }

    // --- 2. STANDARD CARD RENDERER (Fallback / Single Items) ---
    // If it's not a carousel list (e.g. single task, outfit, script), render specific card layouts.

    // Helper: Determine visual emphasis based on priority
    const getPriorityStyle = () => {
        if (priority === 'high') return { borderLeftWidth: 4, borderLeftColor: theme.colors.primary };
        if (priority === 'medium') return { borderLeftWidth: 4, borderLeftColor: theme.colors.secondary };
        return {};
    };
    
    // Helper to handle button clicks (Action Logic)
    const handleAction = () => {
        if ((type === 'place_card' || type === 'travel_idea') && content.locationName) {
             const query = encodeURIComponent(content.locationName);
             Linking.openURL(`https://www.google.com/maps/search/?api=1&query=${query}`);
        } else {
             Alert.alert(title, actionLabel || "Action triggered!");
        }
    };

    // Render logic based on widget.type
    switch (type) {
        
        // ============================================================
        // 📍 TYPE: Single Location / Travel Idea
        // (For cases where AI returns a single spot instead of a list)
        // ============================================================
        case 'place_card': // Fallback if no items array
        case 'travel_idea':
            return (
                <MyCard variant="elevated" style={[styles.card, getPriorityStyle()]}>
                    <View style={styles.headerRow}>
                        <View style={[styles.iconContainer, { backgroundColor: '#E3F2FD' }]}>
                            <Ionicons 
                                name={type === 'travel_idea' ? 'airplane' : 'location'} 
                                size={24} 
                                color="#2196F3" 
                            />
                        </View>
                        <View style={styles.headerText}>
                            <Text style={styles.title}>{title}</Text>
                            {content.locationName && (
                                <Text style={styles.subtitle}>{content.locationName}</Text>
                            )}
                        </View>
                    </View>
                    
                    <Text style={styles.body}>{content.reason || content.description}</Text>
                    
                    {content.address && (
                        <Text style={styles.metaText}>{content.address}</Text>
                    )}
                    
                    <TouchableOpacity style={styles.actionButton} onPress={handleAction}>
                        <Text style={styles.actionButtonText}>
                            {actionLabel || 'View on Map'}
                        </Text>
                        <Ionicons name="arrow-forward" size={16} color={theme.colors.primary} />
                    </TouchableOpacity>
                </MyCard>
            );

        // ============================================================
        // 👔 TYPE: Lifestyle & Visuals (Gradient Cards)
        // (outfit_guide, recipe_card)
        // ============================================================
        case 'outfit_guide':
        case 'recipe_card':
            const isRecipe = type === 'recipe_card';
            return (
                <MyCard 
                    variant="gradient" 
                    // Pink gradient for food, Blue/Purple for fashion
                    gradientColors={isRecipe ? ['#FF9A9E', '#FECFEF'] : ['#a8c0ff', '#3f2b96']} 
                    style={styles.card}
                >
                    <View style={styles.headerRow}>
                        <Text style={[styles.title, { color: '#FFF' }]}>
                            {title} {isRecipe ? '🍳' : '👔'}
                        </Text>
                    </View>
                    
                    <Text style={[styles.body, { color: '#EEE', marginTop: 8 }]}>
                        {content.description}
                    </Text>

                    {/* Tags (Ingredients or Styles) */}
                    <View style={styles.tagContainer}>
                        {(content.styleTags || content.ingredients)?.map((tag: string, i: number) => (
                            <View key={i} style={styles.tag}>
                                <Text style={styles.tagText}>#{tag}</Text>
                            </View>
                        ))}
                    </View>
                </MyCard>
            );
        
        // ============================================================
        // 💬 TYPE: Communication & Scripts (Text Focus)
        // (ice_breaker, discussion_topic, communication_script, etc.)
        // ============================================================
        case 'ice_breaker':
        case 'discussion_topic':
        case 'communication_script':
        case 'apology_template':
        case 'conflict_resolution':
            return (
                <MyCard style={[styles.card, { borderColor: theme.colors.primary, borderWidth: 1 }]}>
                    <Text style={[styles.subtitle, { color: theme.colors.primary, marginBottom: 8, fontWeight: 'bold', textTransform: 'uppercase' }]}>
                        {type.replace('_', ' ')}
                    </Text>
                    
                    {/* The "Script" or "Quote" */}
                    <View style={styles.quoteBox}>
                        <Text style={styles.quoteText}>
                            "{content.text || content.question || content.scriptLines?.join('\n')}"
                        </Text>
                    </View>
                    
                    {content.tips && (
                         <Text style={[styles.metaText, { marginTop: 8 }]}>💡 Tip: {content.tips}</Text>
                    )}

                    <Text style={[styles.subtitle, { marginTop: 10, fontSize: 12, textAlign: 'right' }]}>
                        — {title}
                    </Text>
                </MyCard>
            );

        // ============================================================
        // ✅ TYPE: Actions & Self Care (Checkboxes)
        // (task_card, love_language_act, journal_prompt, etc.)
        // ============================================================
        case 'task_card':
        case 'love_language_act':
        case 'intimacy_exercise':
        case 'journal_prompt':
        case 'meditation_exercise':
            return (
                <MyCard style={[styles.card, getPriorityStyle()]}>
                    <View style={{ flexDirection: 'row', alignItems: 'center' }}>
                        {/* Checkbox Placeholder */}
                        <TouchableOpacity style={styles.checkboxPlaceholder} onPress={() => Alert.alert("Done", "Great job!")} />
                        
                        <View style={{ flex: 1 }}>
                            <Text style={styles.title}>{title}</Text>
                            <Text style={styles.subtitle}>{content.description || content.prompt}</Text>
                        </View>
                    </View>

                    {actionLabel && (
                        <TouchableOpacity style={[styles.actionButton, { marginLeft: 36 }]} onPress={handleAction}>
                            <Text style={styles.actionButtonText}>{actionLabel}</Text>
                        </TouchableOpacity>
                    )}
                </MyCard>
            );

        // ============================================================
        // 🎁 TYPE: Info Cards & Ideas
        // (gift_guide, date_idea, finance_tip)
        // ============================================================
        case 'gift_guide':
        case 'date_idea':
        case 'finance_tip':
            return (
                <MyCard variant="elevated" style={[styles.card, getPriorityStyle()]}>
                    <Text style={styles.title}>{title} ✨</Text>
                    <Text style={styles.body}>{content.description || content.idea || content.tip}</Text>
                    
                    {content.priceRange && (
                        <View style={styles.badge}>
                            <Text style={styles.badgeText}>Cost: {content.priceRange}</Text>
                        </View>
                    )}
                </MyCard>
            );

        // ============================================================
        // ❓ Fallback (For unknown types)
        // ============================================================
        default:
            return (
                <MyCard style={styles.card}>
                    <Text style={styles.title}>{title}</Text>
                    <Text style={styles.body}>
                        {typeof content === 'string' ? content : 'Content loaded via Gemini'}
                    </Text>
                </MyCard>
            );
    }
};

const styles = StyleSheet.create({
    card: {
        marginBottom: 16,
    },
    headerRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 8,
    },
    iconContainer: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: theme.colors.primary + '15', // 15% opacity
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 12,
    },
    headerText: {
        flex: 1,
    },
    title: {
        fontSize: 18,
        fontWeight: 'bold',
        color: theme.colors.text,
    },
    subtitle: {
        fontSize: 14,
        color: theme.colors.textLight,
        marginTop: 2,
    },
    body: {
        fontSize: 15,
        color: theme.colors.text,
        lineHeight: 22,
        marginTop: 8,
    },
    metaText: {
        fontSize: 12,
        color: theme.colors.textLight,
        fontStyle: 'italic',
    },
    // Tag Styles
    tagContainer: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        marginTop: 12,
        gap: 8,
    },
    tag: {
        backgroundColor: 'rgba(255,255,255,0.2)',
        paddingHorizontal: 10,
        paddingVertical: 5,
        borderRadius: 12,
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.4)',
    },
    tagText: {
        color: '#FFF',
        fontSize: 12,
        fontWeight: 'bold',
    },
    // Action Button Styles
    actionButton: {
        flexDirection: 'row',
        alignItems: 'center',
        marginTop: 16,
        alignSelf: 'flex-start',
        backgroundColor: '#F0F2F5',
        paddingVertical: 8,
        paddingHorizontal: 12,
        borderRadius: 20,
    },
    actionButtonText: {
        color: theme.colors.primary,
        fontWeight: 'bold',
        marginRight: 4,
        fontSize: 12,
    },
    // Quote Styles
    quoteBox: {
        backgroundColor: '#FAFAFA',
        padding: 16,
        borderRadius: 12,
        marginTop: 8,
        borderLeftWidth: 3,
        borderLeftColor: theme.colors.primary,
    },
    quoteText: {
        fontSize: 16,
        fontStyle: 'italic',
        color: theme.colors.text,
        lineHeight: 24,
        textAlign: 'center',
    },
    // Checkbox
    checkboxPlaceholder: {
        width: 24,
        height: 24,
        borderRadius: 12,
        borderWidth: 2,
        borderColor: theme.colors.border,
        marginRight: 12,
    },
    // Badge
    badge: {
        marginTop: 10,
        backgroundColor: theme.colors.background,
        paddingHorizontal: 8,
        paddingVertical: 4,
        borderRadius: 4,
        alignSelf: 'flex-start',
    },
    badgeText: {
        fontSize: 12,
        color: theme.colors.textLight,
        fontWeight: 'bold',
    }
});